export const REPOS_BY_KEYWORD_GET = 'REPOS_BY_KEYWORD_GET';
export const REPOS_BY_KEYWORD_REQUEST = 'REPOS_BY_KEYWORD_REQUEST';
export const REPOS_BY_KEYWORD_SUCCESS = 'REPOS_BY_KEYWORD_SUCCESS';
export const REPOS_BY_KEYWORD_FAIL = 'REPOS_BY_KEYWORD_FAIL';
export const REPOS_BY_KEYWORD_RESET = 'REPOS_BY_KEYWORD_RESET';