export const SEARCH_USERS_GET = 'SEARCH_USERS_GET';
export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_USERS_RESET = 'SEARCH_USERS_RESET';