export const USERS_BY_KEYWORD_GET = 'USERS_BY_KEYWORD_GET';
export const USERS_BY_KEYWORD_REQUEST = 'USERS_BY_KEYWORD_REQUEST';
export const USERS_BY_KEYWORD_SUCCESS = 'USERS_BY_KEYWORD_SUCCESS';
export const USERS_BY_KEYWORD_FAIL = 'USERS_BY_KEYWORD_FAIL';
export const USERS_BY_KEYWORD_RESET = 'USERS_BY_KEYWORD_RESET';