export const POPULAR_REPOS_GET = 'POPULAR_REPOS_GET';
export const POPULAR_REPOS_REQUEST = 'POPULAR_REPOS_REQUEST';
export const POPULAR_REPOS_SUCCESS = 'POPULAR_REPOS_SUCCESS';
export const POPULAR_REPOS_FAIL = 'POPULAR_REPOS_FAIL';
export const POPULAR_REPOS_RESET = 'POPULAR_REPOS_RESET';